# This file defines how the client interact with the server
Server_IP: "172.31.34.6"       # This IP address is only accessible via local Wi-Fi network.
ServerPort : 2222
BufferSize : 2048
ChunkSize : 1024
Path_Tesseract: 'C:\Program Files\Tesseract-OCR\tesseract.exe'        # Please define the path to the tesseract on your PC
PH_Whitelist: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

# Parameters for ROI, Hard-coded workflow only
ROI_X: 1350
ROI_Y: 1050
ROI_W:  150
ROI_H:  150