# This file defines how the client interact with the server
Server_IP: "172.31.32.46"       # This IP address is only accessible via local Wi-Fi network.
ServerPort : 2222
BufferSize : 2048
ChunkSize : 1024
Path_Tesseract: 'C:\Program Files\Tesseract-OCR\tesseract.exe'        # Please define the path to the tesseract on your PC
#PH_Whitelist: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]                 #
# PH_Whitelist: [5.5, 5.8, 6.0, 6.2, 6.4, 6.6, 6.8, 7.0, 7.2, 7.4, 7.6, 8.0]                  # pH 5.5 to 8.0
PH_Whitelist: [0.0, 0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0, 5.5, 6.0]                 #

# Parameters for ROI, Hard-coded workflow only
ROI_X: 1350
ROI_Y: 1050
ROI_W:  150
ROI_H:  150