# Logger settings for the logger.py
version: 1
disable_existing_loggers: False

formatters:
  simple:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

handlers:
  file_handler:
    class: logging.FileHandler
    level: DEBUG
    formatter: simple
    filename: "example.log"   # The script will place this in ~/Projects/Logs/example.log

loggers:
  my_logger:
    level: DEBUG
    handlers: [file_handler]
    propagate: False